version: '3'
services:
  igmpproxy:
    image: huntastikus/igmpproxy
    container_name: igmpproxy
    network_mode: "host"
    privileged: true
    networks:
      vlan3:
        ipv4_address: 192.168.3.1
      vlan4:
        ipv4_address: 192.168.4.1
    volumes:
      - ./igmpproxy.conf:/etc/igmpproxy/igmpproxy.conf
    restart: unless-stopped

networks:
  vlan3:
    driver: macvlan
    driver_opts:
      parent: eth0.3
    ipam:
      config:
        - subnet: 192.168.3.0/24
  vlan4:
    driver: macvlan
    driver_opts:
      parent: eth0.4
    ipam:
      config:
        - subnet: 192.168.4.0/24
